'use client';

import React from 'react';
// Assuming these components exist and provide appropriate layout/height
import { DefaultHeader } from '@/components/DefaultHeader';
import { NavbarLeagues } from '@/components/NavbarLeagues';

export default function OceeParkFieldStatusPage() {
  // URL for the iframe source, updated to the new target fragment identifier.
  // NOTE: This ID looks like it might be auto-generated by a framework (ASP.NET).
  // It could change if the source website is updated.
  const fieldStatusUrl = "https://www.oceepark.com/home#ctl00_ContentPlaceHolder1_HomeControlControl_ctl04_ctl03"; // <-- Updated ID

  return (
    // Outermost container: Full screen height, flex column layout.
    <div className="flex flex-col h-screen items-center mx-auto max-w-[500px]">
      <DefaultHeader />

      {/* Main content area: Takes up remaining space */}
      {/* The flex-grow ensures this div fills space between header and navbar */}
      {/* w-full ensures it spans the width */}
      <div className="flex-grow w-full relative flex flex-col px-4 py-4 items-center justify-center"> {/* Added items-center justify-center */}

        {/* Container div matching .iframe-container styles */}
        {/* Centered using mx-auto, max-width applied */}
        {/* Height set to h-[350px] based on previous update */}
        <div className="w-full max-w-[450px] h-[350px] overflow-hidden border-2 border-[#cc0000] box-border mx-auto">
          {/* The iframe itself */}
          <iframe
            src={fieldStatusUrl} // Uses the updated URL
            title="Ocee Park - Specific Section with Offset"
            // Basic classes for block display, full width, no border
            className="block w-full border-none"
            // Inline styles matching the HTML artifact for height and offset
            // Height calculation uses 350px container height
            style={{
              height: '350px', // Height = container height
            }}
            // Sandbox for security - restricts iframe capabilities
            sandbox="allow-same-origin allow-scripts allow-popups allow-popups-to-escape-sandbox"
          >
            {/* Fallback content if iframe fails to load or is blocked */}
            Your browser does not support iframes, or the content is blocked.
          </iframe>
        </div>

        {/* Optional: Add other content here if needed within the scrollable area */}

      </div>

      <NavbarLeagues />
    </div>
  );
}
